name = "CommonSolve"
uuid = "38540f10-b2f7-11e9-35d8-d573e4eb0ff2"
authors = ["Chris Rackauckas <accounts@chrisrackauckas.com>"]
version = "0.2.5"

[compat]
Aqua = "0.8"
SafeTestsets = "0.1"
Test = "1"
julia = "1.10"

[extras]
Aqua = "4c88cf16-eb10-579e-8560-4a9242c79595"
Test = "8dfed614-e22c-5e08-85e1-65c5234f0b40"
SafeTestsets = "1bc83da4-3b8d-516f-aca4-4fe02f6d838f"

[targets]
test = ["Aqua", "SafeTestsets", "Test"]
